<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Modules\Catalog\ConfiOS.Modules.Catalog.Domain\ConfiOS.Modules.Catalog.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Catalog\ConfiOS.Modules.Catalog.Infrastructure\ConfiOS.Modules.Catalog.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>

</Project>
