<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\ConfiOS.BuildingBlocks.Application\ConfiOS.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\ConfiOS.Modules.Catalog.Domain\ConfiOS.Modules.Catalog.Domain.csproj" />
  </ItemGroup>

</Project>
