// <auto-generated />
using System;
using ConfiOS.Modules.Catalog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConfiOS.Modules.Catalog.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260811101648_ProductPackagingAndPricing")]
    partial class ProductPackagingAndPricing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConfiOS.BuildingBlocks.Infrastructure.Auditing.AuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("action");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("Summary")
                        .HasColumnType("jsonb")
                        .HasColumnName("summary");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_records");

                    b.HasIndex("TenantId", "RecordedAt")
                        .HasDatabaseName("ix_audit_records_tenant_id_recorded_at");

                    b.HasIndex("TenantId", "EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_records_tenant_id_entity_type_entity_id");

                    b.ToTable("audit_records", "catalog");
                });

            modelBuilder.Entity("ConfiOS.BuildingBlocks.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("PayloadType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("payload_type");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_outbox_messages_tenant_id");

                    b.HasIndex("ProcessedAt", "OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_unprocessed");

                    b.ToTable("outbox_messages", "catalog");
                });

            modelBuilder.Entity("ConfiOS.Modules.Catalog.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseUnitCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("base_unit_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsReturnable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_returnable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sku");

                    b.Property<string>("TaxClass")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tax_class");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_products_tenant_id");

                    b.HasIndex("TenantId", "Sku")
                        .IsUnique()
                        .HasDatabaseName("ix_products_tenant_id_sku");

                    b.ToTable("products", "catalog");
                });

            modelBuilder.Entity("ConfiOS.Modules.Catalog.Domain.Products.Product", b =>
                {
                    b.OwnsOne("ConfiOS.BuildingBlocks.Domain.ValueObjects.Money", "CostPrice", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("cost_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("cost_currency");

                            b1.HasKey("ProductId");

                            b1.ToTable("products", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("ProductId")
                                .HasConstraintName("fk_products_products_id");
                        });

                    b.OwnsOne("ConfiOS.BuildingBlocks.Domain.ValueObjects.Money", "DepositPerBaseUnit", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("deposit_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("deposit_currency");

                            b1.HasKey("ProductId");

                            b1.ToTable("products", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("ProductId")
                                .HasConstraintName("fk_products_products_id");
                        });

                    b.OwnsOne("ConfiOS.BuildingBlocks.Domain.ValueObjects.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("price_currency");

                            b1.HasKey("ProductId");

                            b1.ToTable("products", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("ProductId")
                                .HasConstraintName("fk_products_products_id");
                        });

                    b.OwnsMany("ConfiOS.Modules.Catalog.Domain.Products.Packaging", "Packagings", b1 =>
                        {
                            b1.Property<Guid>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Barcode")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("barcode");

                            b1.Property<int>("QuantityInBaseUnit")
                                .HasColumnType("integer")
                                .HasColumnName("quantity_in_base_unit");

                            b1.Property<string>("UnitCode")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("unit_code");

                            b1.Property<Guid>("product_id")
                                .HasColumnType("uuid")
                                .HasColumnName("product_id");

                            b1.HasKey("id")
                                .HasName("pk_product_packagings");

                            b1.HasIndex("product_id", "UnitCode")
                                .IsUnique()
                                .HasDatabaseName("ix_product_packagings_product_id_unit_code");

                            b1.ToTable("product_packagings", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("product_id")
                                .HasConstraintName("fk_product_packagings_products_product_id");

                            b1.OwnsOne("ConfiOS.BuildingBlocks.Domain.ValueObjects.Money", "CostPrice", b2 =>
                                {
                                    b2.Property<Guid>("Packagingid")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("cost_price_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("cost_price_currency");

                                    b2.HasKey("Packagingid");

                                    b2.ToTable("product_packagings", "catalog");

                                    b2.WithOwner()
                                        .HasForeignKey("Packagingid")
                                        .HasConstraintName("fk_product_packagings_product_packagings_id");
                                });

                            b1.OwnsOne("ConfiOS.BuildingBlocks.Domain.ValueObjects.Money", "SellingPrice", b2 =>
                                {
                                    b2.Property<Guid>("Packagingid")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("selling_price_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("selling_price_currency");

                                    b2.HasKey("Packagingid");

                                    b2.ToTable("product_packagings", "catalog");

                                    b2.WithOwner()
                                        .HasForeignKey("Packagingid")
                                        .HasConstraintName("fk_product_packagings_product_packagings_id");
                                });

                            b1.Navigation("CostPrice");

                            b1.Navigation("SellingPrice")
                                .IsRequired();
                        });

                    b.Navigation("CostPrice");

                    b.Navigation("DepositPerBaseUnit");

                    b.Navigation("Packagings");

                    b.Navigation("Price")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
